apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: default
labels:
  app: cpu-stress
spec:
  containers:
  - name: stress
    image: progrium/stress
    args: ["--cpu", "4", "--timeout", "300s"] # 4 CPU workers for 5 mins

