name: Deploy resources on eks
on:
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_REGION: ap-south-1 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest' # default is latest stable
        
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name neel-2025 --region eu-west-1

    - name: Deploy app-deploy helm chart to EKS
      run: |
        helm upgrade --install flaskdeploy ./app-deploy \
          --namespace neel \
          --create-namespace \
          --wait
