name: EKS Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (plan/apply/destroy)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1   # change this to your AWS region
      TF_VERSION: 1.12.2        # change if needed

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Terraform Init (inside eks folder)
      - name: Terraform Init
        working-directory: eks
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        working-directory: eks
        run: terraform validate

      # Step 6: Conditional Terraform Actions
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: eks
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: eks
        run: terraform apply -auto-approve tfplan || terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: eks
        run: terraform destroy -auto-approve
